-- CreateEnum
CREATE TYPE "Vertical" AS ENUM ('CHURCH', 'INDEPENDENT_SCHOOL', 'ACE_SCHOOL', 'STATE_SCHOOL', 'NURSERY', 'CHARITY', 'CLUB');

-- CreateEnum
CREATE TYPE "Module" AS ENUM ('FINANCE', 'EVENTS', 'TRANSPORT', 'MEALS', 'ASSET_MANAGEMENT', 'HR', 'AI_WORKSPACE', 'ADVANCED_REPORTING');

-- CreateEnum
CREATE TYPE "ModuleStatus" AS ENUM ('ACTIVE', 'EXPIRED', 'CANCELLED');
