import { regulationsScreens } from "./regulations-wireframes";
import type {
  AppTab,
  FlowGroupId,
  Tone,
  WireframeBlock,
  WireframeScreen,
} from "./wireframe-types";

export type {
  AppTab,
  FlowGroupId,
  Tone,
  WireframeBlock,
  WireframeScreen,
} from "./wireframe-types";

export const flowGroups: Array<{
  id: FlowGroupId;
  label: string;
  summary: string;
}> = [
  {
    id: "setup",
    label: "First-run setup",
    summary: "Three clear actions before Family Week becomes home.",
  },
  {
    id: "week-today",
    label: "Week & Today",
    summary: "Plan the week, follow today, then capture learning quickly.",
  },
  {
    id: "progress",
    label: "Progress & reports",
    summary: "Turn everyday learning and evidence into a trusted record.",
  },
  {
    id: "community-families",
    label: "Community · families",
    summary:
      "Opt in safely, find compatible families and exchange a mutual hello.",
  },
  {
    id: "community-conversations",
    label: "Community · conversations",
    summary: "Adult-only introductions, channels and useful discussion.",
  },
  {
    id: "community-meetups",
    label: "Community · meetups & safety",
    summary: "Discover public meetups with clear privacy and safety controls.",
  },
  {
    id: "family-settings",
    label: "Family & settings",
    summary:
      "Children, permissions, preferences, membership and data controls.",
  },
  {
    id: "regulations-evidence",
    label: "Family · regulations & evidence",
    summary:
      "Verified guidance, prepared evidence, correspondence and controlled sharing.",
  },
  {
    id: "moderation",
    label: "Moderation",
    summary: "Evidence-led review, action history and auditable resolutions.",
  },
];

const notice = (
  title: string,
  body: string,
  tone: Tone = "mint",
): WireframeBlock => ({ type: "notice", title, body, tone });

const card = (
  title: string,
  body: string,
  meta?: string,
  action?: string,
  tone: Tone = "neutral",
  target?: string,
): WireframeBlock => ({
  type: "card",
  title,
  body,
  meta,
  action,
  tone,
  target,
});

const fields = (values: Array<[string, string, string?]>): WireframeBlock => ({
  type: "fields",
  fields: values.map(([label, value, helper]) => ({ label, value, helper })),
});

const chips = (
  items: string[],
  active: string[] = [],
  label?: string,
): WireframeBlock => ({ type: "chips", items, active, label });

const list = (
  items: Array<[string, string?, string?, string?]>,
  title?: string,
): WireframeBlock => ({
  type: "list",
  title,
  items: items.map(([itemTitle, detail, meta, target]) => ({
    title: itemTitle,
    detail,
    meta,
    target,
  })),
});

const stats = (items: Array<[string, string]>): WireframeBlock => ({
  type: "stats",
  items: items.map(([value, label]) => ({ value, label })),
});

export const wireframeScreens: WireframeScreen[] = [
  {
    id: "welcome",
    group: "setup",
    eyebrow: "Welcome",
    title: "Bring structure to home learning",
    description:
      "A calm week plan, trusted records and a community of families — all in one place.",
    blocks: [
      notice(
        "Know what to do next",
        "Start with three small setup steps. Your family week is ready straight afterwards.",
      ),
      card(
        "Your week, organised",
        "Learning, tasks and appointments are visible without turning home into school.",
        "1 place",
      ),
      card(
        "Your people, nearby",
        "Community is optional, adult-only and designed around mutual introductions.",
        "Private",
        undefined,
        "yellow",
      ),
    ],
    primaryAction: "Set up my family",
    primaryTarget: "account-create",
    secondaryAction: "I already have an account",
  },
  {
    id: "account-create",
    group: "setup",
    eyebrow: "Account",
    title: "Create your parent account",
    description: "One secure account for your family organisation.",
    blocks: [
      fields([
        ["Email address", "parent@example.com"],
        ["Password", "••••••••••••", "Use at least 12 characters."],
      ]),
      notice(
        "Privacy at a glance",
        "Family records stay private. Community never exposes child profiles.",
      ),
    ],
    primaryAction: "Create account",
    primaryTarget: "email-verify",
    secondaryAction: "Sign in or recover account",
  },
  {
    id: "email-verify",
    group: "setup",
    eyebrow: "Account",
    title: "Check your inbox",
    description: "We sent a six-digit code to parent@example.com.",
    blocks: [
      fields([["Verification code", "4  8  2  1  9  6"]]),
      notice(
        "Why verify?",
        "It protects family records and lets you recover the account safely.",
        "neutral",
      ),
      card(
        "No email yet?",
        "Send a new code or use a different address.",
        undefined,
        "Resend code",
      ),
    ],
    primaryAction: "Verify email",
    primaryTarget: "children-list",
    secondaryAction: "Use a different email",
  },
  {
    id: "account-recover",
    group: "setup",
    eyebrow: "Account recovery",
    title: "Get back into your account",
    description: "We will send a secure recovery link if the address matches.",
    blocks: [
      fields([["Email address", "parent@example.com"]]),
      notice(
        "Private response",
        "For security, the confirmation looks the same whether or not an account exists.",
        "neutral",
      ),
    ],
    primaryAction: "Send recovery link",
    primaryTarget: "account-create",
    secondaryAction: "Back to sign in",
  },
  {
    id: "children-list",
    group: "setup",
    eyebrow: "Setup · 1 of 3",
    title: "Who are you organising for?",
    description: "Start with one child. Add or change details later.",
    blocks: [
      card("Maya", "Age 9 · Year 4 equivalent", "Child 1", "Edit details"),
      card(
        "Add another child",
        "A first name or nickname and age are enough to begin.",
        undefined,
        "Add child",
        "mint",
      ),
    ],
    primaryAction: "Continue with 1 child",
    primaryTarget: "child-add",
  },
  {
    id: "child-add",
    group: "setup",
    eyebrow: "Setup · 1 of 3",
    title: "Add a child",
    description: "We only ask for what helps organise learning.",
    blocks: [
      fields([
        ["First name or nickname", "Maya"],
        ["Age", "9"],
        ["Learning stage (optional)", "Year 4 equivalent"],
      ]),
      notice(
        "Private by default",
        "Child names, ages, plans and evidence never appear in Community.",
      ),
    ],
    primaryAction: "Save child",
    primaryTarget: "learning-days",
  },
  {
    id: "learning-days",
    group: "setup",
    eyebrow: "Setup · 2 of 3",
    title: "Choose your learning days",
    description: "This shapes Week. You can still learn on any day.",
    blocks: [
      chips(
        ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        ["Mon", "Tue", "Wed", "Thu"],
        "Tap to include",
      ),
      card(
        "Four-day rhythm",
        "Monday to Thursday are highlighted. Friday remains flexible.",
        "Suggested",
        undefined,
        "mint",
      ),
    ],
    primaryAction: "Use these days",
    primaryTarget: "first-activity",
    secondaryAction: "Choose later",
  },
  {
    id: "first-activity",
    group: "setup",
    eyebrow: "Setup · 3 of 3",
    title: "Plan your first activity",
    description: "Give tomorrow one useful anchor. Everything else can wait.",
    blocks: [
      fields([
        ["Activity", "Fractions with pancakes"],
        ["Child", "Maya"],
      ]),
      chips(["Tomorrow", "10:00", "45 min"], ["Tomorrow", "10:00", "45 min"]),
      card(
        "Optional details",
        "Add a subject, resources or notes later from the activity.",
        undefined,
        "Add details",
      ),
    ],
    primaryAction: "Add to our week",
    primaryTarget: "setup-complete",
  },
  {
    id: "setup-complete",
    group: "setup",
    eyebrow: "Setup complete",
    title: "Your family week is ready",
    description: "From now on, NexSteps Home opens here.",
    tab: "Week",
    blocks: [
      {
        type: "week",
        activeDay: "Tue",
        days: [
          { day: "Mon", date: "28", count: 2 },
          { day: "Tue", date: "29", count: 1 },
          { day: "Wed", date: "30", count: 2 },
          { day: "Thu", date: "31", count: 1 },
          { day: "Fri", date: "1" },
        ],
      },
      card(
        "Tomorrow · 10:00",
        "Fractions with pancakes\nMaya · Maths · 45 minutes",
        "Next",
        "Open activity",
        "mint",
      ),
      notice(
        "You are set up",
        "There is no tutorial or checklist in the way — just the family week.",
        "yellow",
      ),
    ],
    primaryAction: "Open Family Week",
    primaryTarget: "week-home",
  },
  {
    id: "week-home",
    group: "week-today",
    eyebrow: "Week",
    title: "28 July – 1 August",
    description: "A single view of learning, tasks and family commitments.",
    tab: "Week",
    blocks: [
      {
        type: "week",
        activeDay: "Tue",
        days: [
          { day: "Mon", date: "28", count: 2 },
          { day: "Tue", date: "29", count: 3 },
          { day: "Wed", date: "30", count: 2 },
          { day: "Thu", date: "31", count: 1 },
          { day: "Fri", date: "1" },
        ],
      },
      card(
        "10:00 · Fractions with pancakes",
        "Maya · Maths · 45 minutes",
        "Learning",
        "Open",
        "mint",
      ),
      card(
        "14:00 · Library visit",
        "Whole family · Bring returns",
        "Calendar",
        "Open",
      ),
      card(
        "Renew library books",
        "Due today · Assigned to Sam",
        "Task",
        "Complete",
        "yellow",
      ),
    ],
    primaryAction: "Add to week",
    primaryTarget: "day-detail",
  },
  {
    id: "day-detail",
    group: "week-today",
    eyebrow: "Week · Tuesday",
    title: "Tuesday 29 July",
    description: "Everything for the day, ordered by time and importance.",
    tab: "Week",
    blocks: [
      list(
        [
          ["Fractions with pancakes", "10:00 · Maya · Maths", "45 min"],
          ["Renew library books", "Before 13:00 · Sam", "Task"],
          ["Library visit", "14:00 · Whole family", "Calendar"],
        ],
        "Planned",
      ),
      notice(
        "Keep the day realistic",
        "Two learning activities is the suggested maximum for Maya today.",
        "yellow",
      ),
    ],
    primaryAction: "Plan activity",
    primaryTarget: "activity-plan",
    secondaryAction: "Add task or calendar item",
  },
  {
    id: "activity-plan",
    group: "week-today",
    eyebrow: "Plan activity",
    title: "Add learning to the week",
    description: "Only the essentials are required.",
    tab: "Week",
    blocks: [
      fields([
        ["Activity", "Nature journal walk"],
        ["Child", "Maya"],
        ["Date and time", "Wednesday · 11:00"],
        ["Duration", "60 minutes"],
      ]),
      chips(["Science", "English", "Art"], ["Science", "English"], "Subjects"),
      card(
        "Resources (optional)",
        "Notebook, pencils and phone camera.",
        undefined,
        "Add resource",
      ),
    ],
    primaryAction: "Save activity",
    primaryTarget: "activity-detail",
  },
  {
    id: "activity-detail",
    group: "week-today",
    eyebrow: "Activity",
    title: "Nature journal walk",
    description: "Wednesday · 11:00 · Maya",
    tab: "Week",
    blocks: [
      chips(["Science", "English"], ["Science", "English"]),
      card(
        "Plan",
        "Notice three plants, sketch one and write two observations.",
        "60 min",
      ),
      card("Resources", "Notebook · pencils · phone camera", undefined, "Edit"),
      notice(
        "Ready to begin",
        "When finished, add a quick learning log and optional evidence.",
      ),
    ],
    primaryAction: "Start activity",
    primaryTarget: "quick-log",
    secondaryAction: "Edit activity",
  },
  {
    id: "today",
    group: "week-today",
    eyebrow: "Today",
    title: "Good morning, Sam",
    description: "Three things deserve your attention today.",
    tab: "Today",
    blocks: [
      stats([
        ["2", "Learning"],
        ["1", "Task"],
        ["1", "Appointment"],
      ]),
      card(
        "Next · 10:00",
        "Fractions with pancakes\nMaya · Maths",
        "45 min",
        "Open",
        "mint",
      ),
      card(
        "Later · 14:00",
        "Library visit · Whole family",
        "Calendar",
        "Directions",
      ),
      notice(
        "Small win",
        "Yesterday’s nature journal added evidence to Science.",
        "yellow",
      ),
    ],
    primaryAction: "Log learning",
    primaryTarget: "quick-log",
  },
  {
    id: "quick-log",
    group: "week-today",
    eyebrow: "Quick learning log",
    title: "What happened?",
    description: "Capture the useful record in under a minute.",
    tab: "Today",
    blocks: [
      fields([
        ["Activity", "Fractions with pancakes"],
        [
          "What Maya did",
          "Compared halves, quarters and eighths while cooking.",
        ],
      ]),
      chips(
        ["Confident", "Needed help", "Try again"],
        ["Confident"],
        "How did it go?",
      ),
      chips(["Maths", "Life skills"], ["Maths", "Life skills"], "Subjects"),
      card(
        "Evidence (optional)",
        "Add a photo, file or voice note.",
        undefined,
        "Add evidence",
        "mint",
      ),
    ],
    primaryAction: "Save learning log",
    primaryTarget: "progress-overview",
  },
  {
    id: "task-editor",
    group: "week-today",
    eyebrow: "Task",
    title: "Add a family task",
    description: "Keep work around learning visible, without over-planning.",
    tab: "Week",
    blocks: [
      fields([
        ["Task", "Renew library books"],
        ["Assigned to", "Sam"],
        ["Due", "Tuesday · 13:00"],
      ]),
      chips(["Low", "Normal", "Important"], ["Normal"], "Priority"),
    ],
    primaryAction: "Save task",
    primaryTarget: "week-home",
  },
  {
    id: "calendar-editor",
    group: "week-today",
    eyebrow: "Calendar item",
    title: "Add an appointment",
    description: "Family commitments sit alongside learning.",
    tab: "Week",
    blocks: [
      fields([
        ["Title", "Library visit"],
        ["Who", "Whole family"],
        ["Date and time", "Tuesday · 14:00"],
        ["Location", "Northfield Library"],
      ]),
      notice(
        "Location privacy",
        "This private family event is never shared to Community.",
      ),
    ],
    primaryAction: "Add to calendar",
    primaryTarget: "week-home",
  },
  {
    id: "progress-overview",
    group: "progress",
    eyebrow: "Progress · Maya",
    title: "A growing record of learning",
    description: "See patterns without reducing learning to scores.",
    tab: "Progress",
    blocks: [
      stats([
        ["18", "Logs"],
        ["26", "Evidence"],
        ["7", "Subjects"],
      ]),
      card(
        "This week",
        "4 learning logs · 6 evidence items",
        "Active",
        "View history",
        "mint",
      ),
      card(
        "Strongest thread",
        "Maths appears across cooking, budgeting and games.",
        "Insight",
      ),
      card(
        "Next report",
        "Summer term summary can be generated now.",
        "Ready",
        "Create report",
        "yellow",
      ),
    ],
    primaryAction: "View learning history",
    primaryTarget: "learning-history",
  },
  {
    id: "learning-history",
    group: "progress",
    eyebrow: "Progress · History",
    title: "Learning history",
    description: "Searchable, chronological and easy to evidence.",
    tab: "Progress",
    blocks: [
      chips(["All", "Maths", "English", "Science", "Life skills"], ["All"]),
      list([
        ["Fractions with pancakes", "Today · Maths · Life skills", "2 photos"],
        ["Nature journal walk", "Yesterday · Science · English", "3 items"],
        ["Library research", "24 July · English", "1 note"],
        ["Budget a picnic", "22 July · Maths · Life skills", "1 file"],
      ]),
    ],
    primaryAction: "Open latest log",
    primaryTarget: "log-detail",
  },
  {
    id: "log-detail",
    group: "progress",
    eyebrow: "Learning log",
    title: "Fractions with pancakes",
    description: "Today · Maya · logged by Sam",
    tab: "Progress",
    blocks: [
      chips(
        ["Maths", "Life skills", "Confident"],
        ["Maths", "Life skills", "Confident"],
      ),
      card(
        "What happened",
        "Compared halves, quarters and eighths while cooking.",
      ),
      card(
        "Reflection",
        "Maya explained why two quarters equal one half.",
        "Parent note",
      ),
      card(
        "Evidence",
        "2 photos · 1 recipe note",
        undefined,
        "View evidence",
        "mint",
      ),
    ],
    primaryAction: "Edit learning log",
    primaryTarget: "quick-log",
    secondaryAction: "Download record",
  },
  {
    id: "evidence-gallery",
    group: "progress",
    eyebrow: "Progress · Evidence",
    title: "Evidence gallery",
    description: "Photos, files and voice notes stay attached to learning.",
    tab: "Progress",
    blocks: [
      chips(["All", "Photos", "Files", "Voice"], ["All"]),
      list([
        ["Pancake fraction plate", "Today · Photo", "Maths"],
        ["Nature journal page", "Yesterday · Photo", "Science"],
        ["Plant observations", "Yesterday · Voice note", "English"],
        ["Picnic budget", "22 July · PDF", "Maths"],
      ]),
      notice(
        "Private family record",
        "Evidence is not visible to Community members.",
      ),
    ],
    primaryAction: "Add evidence",
    primaryTarget: "evidence-detail-upload",
  },
  {
    id: "evidence-detail-upload",
    group: "progress",
    eyebrow: "Evidence",
    title: "Pancake fraction plate",
    description: "Photo · Today · attached to Fractions with pancakes",
    tab: "Progress",
    blocks: [
      notice(
        "Image preview",
        "Original photo · 3024 × 4032 · stored privately",
        "neutral",
      ),
      fields([["Caption", "Maya labelled halves, quarters and eighths."]]),
      chips(["Maths", "Life skills"], ["Maths", "Life skills"]),
      card(
        "Upload another item",
        "Photo, file or voice note · up to 25 MB",
        undefined,
        "Choose file",
        "mint",
      ),
    ],
    primaryAction: "Save evidence",
    primaryTarget: "evidence-gallery",
    secondaryAction: "Remove evidence",
  },
  {
    id: "subjects",
    group: "progress",
    eyebrow: "Progress · Subjects",
    title: "Learning across subjects",
    description:
      "Subjects organise the record without constraining activities.",
    tab: "Progress",
    blocks: [
      list([
        ["Maths", "7 logs · 12 evidence items", "Active"],
        ["English", "5 logs · 8 evidence items", "Active"],
        ["Science", "4 logs · 5 evidence items", "Active"],
        ["Life skills", "3 logs · 4 evidence items", "Growing"],
        ["Art", "2 logs · 3 evidence items", "Growing"],
      ]),
      card(
        "Add a subject",
        "Use your own name or choose a common subject.",
        undefined,
        "Add subject",
      ),
    ],
    primaryAction: "Open Maths",
    primaryTarget: "learning-history",
  },
  {
    id: "reports-list",
    group: "progress",
    eyebrow: "Progress · Reports",
    title: "Learning reports",
    description: "Create clear summaries for your family or local authority.",
    tab: "Progress",
    blocks: [
      card(
        "Summer term 2026",
        "1 May – 24 July · Maya",
        "Ready",
        "Open report",
        "mint",
      ),
      card(
        "Spring term 2026",
        "8 January – 28 March · Maya",
        "PDF",
        "Download",
      ),
      notice(
        "You stay in control",
        "Review and edit the generated summary before you download or share it.",
        "yellow",
      ),
    ],
    primaryAction: "Create a report",
    primaryTarget: "report-request",
  },
  {
    id: "report-request",
    group: "progress",
    eyebrow: "Create report",
    title: "Choose what to include",
    description: "Start broad, then edit the generated summary.",
    tab: "Progress",
    blocks: [
      fields([
        ["Child", "Maya"],
        ["Period", "Summer term · 1 May – 24 July"],
      ]),
      chips(
        ["Overview", "Subjects", "Selected evidence", "Attendance"],
        ["Overview", "Subjects", "Selected evidence"],
      ),
      notice(
        "Estimated length",
        "About 6 pages from 18 learning logs and 26 evidence items.",
        "neutral",
      ),
    ],
    primaryAction: "Generate draft report",
    primaryTarget: "report-detail-download",
  },
  {
    id: "report-detail-download",
    group: "progress",
    eyebrow: "Report draft",
    title: "Summer term 2026",
    description: "Maya · 1 May – 24 July · draft saved",
    tab: "Progress",
    blocks: [
      stats([
        ["18", "Logs"],
        ["7", "Subjects"],
        ["12", "Selected evidence"],
      ]),
      card(
        "Overview",
        "Maya followed practical interests across maths, science and language.",
        undefined,
        "Edit section",
      ),
      card(
        "Maths",
        "Applied fractions, measures and budgeting in everyday contexts.",
        undefined,
        "Review",
      ),
      notice(
        "Ready when you are",
        "Download a branded PDF or keep editing the saved draft.",
        "mint",
      ),
    ],
    primaryAction: "Download PDF",
    primaryTarget: "reports-list",
    secondaryAction: "Share secure link",
  },
  {
    id: "community-preview",
    group: "community-families",
    eyebrow: "Community",
    title: "Homeschooling is easier together",
    description:
      "Find adults nearby who share your rhythm, interests and values.",
    tab: "Community",
    blocks: [
      card(
        "Nearby families",
        "Browse coarse location, learning approach and parent interests.",
        "Private",
      ),
      card(
        "Useful conversations",
        "Ask questions in moderated topic channels.",
        "Adults only",
      ),
      card(
        "Low-pressure meetups",
        "Discover public and online events before making contact.",
        "Opt in",
        undefined,
        "yellow",
      ),
      notice(
        "Children stay off Community",
        "No child names, ages, schedules or evidence are shared.",
      ),
    ],
    primaryAction: "Explore Community safely",
    primaryTarget: "community-join",
    secondaryAction: "Not now",
  },
  {
    id: "community-join",
    group: "community-families",
    eyebrow: "Join Community",
    title: "Build your adult profile",
    description: "You decide what other homeschooling parents can see.",
    tab: "Community",
    blocks: [
      fields([
        ["Display name", "Sam R."],
        ["Area", "Northfield · approximate"],
        [
          "Short introduction",
          "Learning through projects, books and lots of outdoor time.",
        ],
      ]),
      chips(
        [
          "Project-led",
          "Outdoor learning",
          "Neurodiversity-aware",
          "Faith-neutral",
        ],
        ["Project-led", "Outdoor learning"],
      ),
      notice(
        "Live privacy preview",
        "Only the fields shown below will appear to other adults.",
      ),
    ],
    primaryAction: "Preview my profile",
    primaryTarget: "community-privacy-preview",
  },
  {
    id: "community-privacy-preview",
    group: "community-families",
    eyebrow: "Privacy preview",
    title: "This is what others will see",
    description: "Check every detail before your profile becomes discoverable.",
    tab: "Community",
    blocks: [
      card(
        "Sam R. · Northfield area",
        "Project-led · Outdoor learning\nUsually available weekday afternoons.",
        "Adult profile",
        "Edit",
      ),
      list([
        ["Visible", "Display name · approximate area · interests"],
        ["Hidden", "Child profiles · exact location · family schedule"],
        ["Contact", "Only after both adults exchange a hello"],
      ]),
      notice(
        "You can leave anytime",
        "Pause discovery or delete the Community profile without affecting family records.",
        "yellow",
      ),
    ],
    primaryAction: "Join Community",
    primaryTarget: "community-home",
    secondaryAction: "Edit profile",
  },
  {
    id: "community-home",
    group: "community-families",
    eyebrow: "Community",
    title: "Good people, useful connections",
    description: "A calm starting point — no infinite feed.",
    tab: "Community",
    blocks: [
      card(
        "6 families nearby",
        "Two share your learning approach and weekday availability.",
        "New matches",
        "Browse families",
        "mint",
      ),
      card(
        "Nature club · Friday",
        "Public meetup · Riverside Park · 8 families interested",
        "Meetup",
        "View details",
        "yellow",
      ),
      card(
        "Project-led learning",
        "3 new posts in a channel you follow.",
        "Channel",
        "Open discussion",
      ),
      notice(
        "Your privacy is on",
        "Others see Northfield area, never your exact location.",
      ),
    ],
    primaryAction: "Find families",
    primaryTarget: "family-directory",
  },
  {
    id: "family-directory",
    group: "community-families",
    eyebrow: "Community · Families",
    title: "Families you may connect with",
    description: "Compatibility first; distance stays approximate.",
    tab: "Community",
    blocks: [
      chips(
        ["Nearby", "Shared approach", "Availability", "Interests"],
        ["Nearby"],
      ),
      card(
        "Alex & Jo · 3–5 miles",
        "Project-led · Outdoor learning\nWeekday afternoons",
        "3 shared interests",
        "View profile",
        "mint",
      ),
      card(
        "Priya · 5–10 miles",
        "Literature-rich · Neurodiversity-aware\nTuesday mornings",
        "2 shared interests",
        "View profile",
      ),
      card(
        "Morgan · Online",
        "Unschooling · Creative projects\nFlexible",
        "Online only",
        "View profile",
      ),
    ],
    primaryAction: "View Alex & Jo",
    primaryTarget: "household-profile",
  },
  {
    id: "household-profile",
    group: "community-families",
    eyebrow: "Adult household profile",
    title: "Alex & Jo",
    description: "Northfield area · 3–5 miles away",
    tab: "Community",
    blocks: [
      card(
        "About us",
        "We enjoy project-led learning, woodland walks and relaxed museum trips.",
        "Verified adults",
      ),
      chips(
        ["Project-led", "Outdoor learning", "Museums", "Weekday afternoons"],
        ["Project-led", "Outdoor learning"],
      ),
      list([
        ["What is visible", "Adult names · approximate area · interests"],
        ["What stays private", "Children · exact address · personal contact"],
      ]),
      notice(
        "Make first contact gently",
        "A hello shares one short message. Private chat opens only if they respond.",
      ),
    ],
    primaryAction: "Send a hello",
    primaryTarget: "send-hello",
    secondaryAction: "Save profile",
  },
  {
    id: "send-hello",
    group: "community-families",
    eyebrow: "Send a hello",
    title: "Start with one friendly message",
    description: "No private details are shared yet.",
    tab: "Community",
    blocks: [
      fields([
        [
          "Your message",
          "Hi Alex & Jo — we also love woodland walks. Would you be open to saying hello?",
        ],
      ]),
      notice(
        "What happens next",
        "They can accept, decline or ignore. Private adult chat opens only after acceptance.",
      ),
      card(
        "Your visible profile",
        "Sam R. · Northfield area · Project-led · Outdoor learning",
        "Preview",
      ),
    ],
    primaryAction: "Send hello",
    primaryTarget: "connection-requests",
    secondaryAction: "Cancel",
  },
  {
    id: "connection-requests",
    group: "community-families",
    eyebrow: "Community · Hellos",
    title: "Connection requests",
    description: "Mutual choice before private conversation.",
    tab: "Community",
    blocks: [
      card(
        "From Priya",
        "“We also use lots of books and are often free on Tuesdays.”",
        "Received today",
        "Review",
        "mint",
      ),
      card(
        "To Alex & Jo",
        "Waiting for a response · your message can be withdrawn.",
        "Pending",
        "Withdraw",
      ),
      notice(
        "No pressure",
        "Declines are private. Ignored requests expire after 30 days.",
        "neutral",
      ),
    ],
    primaryAction: "Accept Priya’s hello",
    primaryTarget: "private-intro",
  },
  {
    id: "private-intro",
    group: "community-conversations",
    eyebrow: "Private adult introduction",
    title: "Priya",
    description: "Connected today · Northfield area",
    tab: "Community",
    blocks: [
      {
        type: "message",
        sender: "Priya",
        body: "Thanks for saying hello. We are often at Northfield Library on Tuesday mornings.",
        time: "10:14",
      },
      {
        type: "message",
        sender: "You",
        body: "That could work for us. Shall we both RSVP to the public story circle first?",
        time: "10:18",
        own: true,
      },
      notice(
        "Keep first meetings public",
        "Use a listed meetup or public venue. Share personal details only when comfortable.",
        "yellow",
      ),
      fields([["Message", "Write a reply…"]]),
    ],
    primaryAction: "Send reply",
    primaryTarget: "thread-list",
    secondaryAction: "Block or report",
  },
  {
    id: "channel-list",
    group: "community-conversations",
    eyebrow: "Community · Channels",
    title: "Useful conversations",
    description:
      "Moderated topics, organised for scanning rather than scrolling.",
    tab: "Community",
    blocks: [
      list([
        ["Getting started", "New to home education · 4 new", "Following"],
        ["Project-led learning", "Ideas and examples · 3 new", "Following"],
        ["Local resources", "Libraries, groups and venues · 8 new", "Nearby"],
        [
          "Neurodiversity-aware learning",
          "Adult discussion · 2 new",
          "Moderated",
        ],
        [
          "Curriculum & qualifications",
          "Planning and pathways · 5 new",
          "Popular",
        ],
      ]),
    ],
    primaryAction: "Open Project-led learning",
    primaryTarget: "thread-list",
  },
  {
    id: "thread-list",
    group: "community-conversations",
    eyebrow: "Project-led learning",
    title: "Recent discussions",
    description: "Clear titles make it easy to find useful answers later.",
    tab: "Community",
    blocks: [
      chips(["Recent", "Unanswered", "Saved"], ["Recent"]),
      card(
        "Turning a garden build into maths",
        "5 replies · last reply 20 min ago",
        "Popular",
        "Open",
      ),
      card(
        "Gentle ways to document projects",
        "2 replies · started by Morgan",
        "New",
        "Open",
      ),
      card(
        "Museum project ideas for mixed ages",
        "8 replies · saved by 12 parents",
        "Saved often",
        "Open",
      ),
    ],
    primaryAction: "Open garden build thread",
    primaryTarget: "thread-detail",
    secondaryAction: "Start discussion",
  },
  {
    id: "thread-detail",
    group: "community-conversations",
    eyebrow: "Project-led learning",
    title: "Turning a garden build into maths",
    description: "Started by Alex · 5 replies · adult discussion",
    tab: "Community",
    blocks: [
      card(
        "Alex",
        "We measured the beds, priced timber and compared soil volumes. What else would you capture?",
        "Original post",
      ),
      {
        type: "message",
        sender: "Priya",
        body: "Scale drawings worked well for us, plus a photo of the final measurements.",
        time: "09:46",
      },
      {
        type: "message",
        sender: "Morgan",
        body: "We tracked the budget in a simple spreadsheet and wrote a short reflection.",
        time: "10:02",
      },
      notice(
        "Community guideline",
        "Share ideas and adult experience — never identifiable information about children.",
        "neutral",
      ),
    ],
    primaryAction: "Reply",
    primaryTarget: "thread-compose",
    secondaryAction: "Save discussion",
  },
  {
    id: "thread-compose",
    group: "community-conversations",
    eyebrow: "Reply",
    title: "Add something useful",
    description: "The composer keeps guidance visible at the point of posting.",
    tab: "Community",
    blocks: [
      fields([
        [
          "Your reply",
          "We also compared the cost per square metre and estimated how much rainwater the beds might need.",
        ],
      ]),
      notice(
        "Before you post",
        "Keep children anonymous and avoid exact locations, contact details or private schedules.",
        "yellow",
      ),
      card("Posting as", "Sam R. · adult Community profile", "Visible"),
    ],
    primaryAction: "Post reply",
    primaryTarget: "thread-detail",
    secondaryAction: "Save draft",
  },
  {
    id: "meetup-list",
    group: "community-meetups",
    eyebrow: "Community · Meetups",
    title: "Meet in ways that feel comfortable",
    description:
      "Public and online options appear before private arrangements.",
    tab: "Community",
    blocks: [
      chips(["Nearby", "This week", "Online", "Saved"], ["Nearby"]),
      card(
        "Nature club",
        "Friday · 10:30 · Riverside Park\n8 families interested",
        "Public venue",
        "View",
        "mint",
      ),
      card(
        "Story circle",
        "Tuesday · 11:00 · Northfield Library\n5 families going",
        "Public venue",
        "View",
      ),
      card(
        "Parent planning coffee",
        "Thursday · 20:00 · Online\nAdults only",
        "Online",
        "View",
        "yellow",
      ),
    ],
    primaryAction: "Open Nature club",
    primaryTarget: "meetup-detail",
    secondaryAction: "Create meetup",
  },
  {
    id: "meetup-detail",
    group: "community-meetups",
    eyebrow: "Meetup",
    title: "Nature club",
    description: "Friday · 10:30–12:00 · Riverside Park",
    tab: "Community",
    blocks: [
      chips(
        ["Outdoor", "All ages", "Public venue"],
        ["Outdoor", "Public venue"],
      ),
      card(
        "What to expect",
        "A relaxed woodland loop, nature bingo and optional picnic.",
        "Hosted by Alex",
      ),
      card(
        "Meeting point",
        "Main visitor centre entrance. Exact map visible after RSVP.",
        "Approximate",
      ),
      stats([
        ["5", "Going"],
        ["3", "Interested"],
        ["12", "Capacity"],
      ]),
      notice(
        "Safety",
        "A parent or guardian stays responsible for their own family throughout.",
        "yellow",
      ),
    ],
    primaryAction: "I’m interested",
    primaryTarget: "meetup-rsvp",
    secondaryAction: "Ask organiser",
  },
  {
    id: "meetup-rsvp",
    group: "community-meetups",
    eyebrow: "RSVP",
    title: "Confirm your interest",
    description: "Only your adult display name appears to other attendees.",
    tab: "Community",
    blocks: [
      chips(["Interested", "Going"], ["Interested"], "Response"),
      fields([
        ["Adults attending", "1"],
        ["Children attending", "2 · count only"],
      ]),
      notice(
        "Attendee privacy",
        "Children are counted for capacity but never named on the attendee list.",
      ),
      card(
        "Cancellation",
        "Change your response at any time. The organiser is notified.",
        "Flexible",
      ),
    ],
    primaryAction: "Save RSVP",
    primaryTarget: "meetup-detail",
  },
  {
    id: "meetup-create",
    group: "community-meetups",
    eyebrow: "Create meetup",
    title: "Invite families to something simple",
    description:
      "Public or online first. Private home addresses are not supported.",
    tab: "Community",
    blocks: [
      fields([
        ["Name", "Sketching at the museum"],
        ["Date and time", "12 August · 11:00"],
        ["Venue", "City Museum · public venue"],
        ["Capacity", "10 families"],
      ]),
      chips(["Public venue", "Online"], ["Public venue"], "Format"),
      notice(
        "Location check",
        "The exact meeting point becomes visible only to confirmed attendees.",
        "yellow",
      ),
    ],
    primaryAction: "Preview meetup",
    primaryTarget: "meetup-manage",
  },
  {
    id: "meetup-manage",
    group: "community-meetups",
    eyebrow: "Manage meetup",
    title: "Sketching at the museum",
    description: "Draft · 12 August · City Museum",
    tab: "Community",
    blocks: [
      stats([
        ["0", "Going"],
        ["10", "Capacity"],
        ["Draft", "Status"],
      ]),
      list([
        ["Details", "Title, description, timing and format", "Complete"],
        ["Location", "Public venue and attendee meeting point", "Complete"],
        ["Guidance", "Adult responsibility and accessibility note", "Complete"],
      ]),
      notice(
        "Before publishing",
        "Meetups can be reported, cancelled and audited by moderators.",
        "neutral",
      ),
    ],
    primaryAction: "Publish meetup",
    primaryTarget: "meetup-list",
    secondaryAction: "Edit draft",
  },
  {
    id: "community-settings",
    group: "community-meetups",
    eyebrow: "Community settings",
    title: "Control your visibility",
    description:
      "Community preferences are separate from private family records.",
    tab: "Community",
    blocks: [
      list([
        ["Profile discoverability", "Visible to adult members", "On"],
        ["Approximate distance", "Show 3–5 mile bands", "On"],
        ["Connection requests", "Allow new hellos", "On"],
        ["Meetup notifications", "Nearby and saved events", "On"],
        ["Channel notifications", "Following only", "On"],
      ]),
      notice(
        "Pause without leaving",
        "Hide your profile and stop new requests while keeping existing connections.",
      ),
    ],
    primaryAction: "Save settings",
    primaryTarget: "community-home",
    secondaryAction: "Pause Community",
  },
  {
    id: "block-report",
    group: "community-meetups",
    eyebrow: "Safety",
    title: "Block or report",
    description: "Immediate protection first; clear follow-up second.",
    tab: "Community",
    blocks: [
      card(
        "Block Priya",
        "Stops messages and hides both profiles from each other immediately.",
        "Private",
        "Block now",
        "danger",
      ),
      card(
        "Report a concern",
        "Send the relevant profile, post, message or meetup to moderators.",
        "Reviewed",
        "Choose reason",
      ),
      chips(
        ["Harassment", "Unsafe meetup", "Privacy", "Spam", "Other"],
        ["Privacy"],
        "Reason",
      ),
      fields([
        [
          "What happened?",
          "A private detail was repeated in a public channel.",
        ],
      ]),
    ],
    primaryAction: "Submit report and block",
    primaryTarget: "report-confirmation",
    secondaryAction: "Block only",
  },
  {
    id: "report-confirmation",
    group: "community-meetups",
    eyebrow: "Report received",
    title: "You are protected",
    description:
      "The member is blocked and your report is in the moderation queue.",
    tab: "Community",
    blocks: [
      notice(
        "Immediate action complete",
        "They cannot message you, view your profile or see your meetups.",
        "mint",
      ),
      card(
        "Reference NSH-4821",
        "Submitted today · Privacy concern · evidence attached",
        "In review",
      ),
      list([
        ["What moderators see", "Reported content and essential context"],
        ["What the member sees", "No reporter identity"],
        ["Updates", "You will be notified when the review is complete"],
      ]),
    ],
    primaryAction: "Return to Community",
    primaryTarget: "community-home",
  },
  {
    id: "family-children",
    group: "family-settings",
    eyebrow: "Family",
    title: "Children",
    description: "Private profiles that shape planning and progress.",
    tab: "Family",
    blocks: [
      {
        type: "card",
        title: "Regulations & Evidence",
        body: "Stay prepared and keep important records together.",
        meta: "2 to review",
        action: "Open",
        target: "regulations-overview",
        tone: "yellow",
      },
      card(
        "Maya",
        "Age 9 · Year 4 equivalent\n4 learning days",
        "Active",
        "Open",
        "mint",
      ),
      card(
        "Leo",
        "Age 6 · Key Stage 1 equivalent\n3 learning days",
        "Active",
        "Open",
      ),
      card(
        "Add a child",
        "A name or nickname and age are enough.",
        undefined,
        "Add child",
        "yellow",
      ),
      notice(
        "Never shared to Community",
        "Child profiles and records stay inside the family account.",
      ),
    ],
    primaryAction: "Open Maya",
    primaryTarget: "child-details",
  },
  {
    id: "child-details",
    group: "family-settings",
    eyebrow: "Family · Maya",
    title: "Child details",
    description: "Personal settings that support the week and learning record.",
    tab: "Family",
    blocks: [
      fields([
        ["Name or nickname", "Maya"],
        ["Age", "9"],
        ["Learning stage", "Year 4 equivalent"],
      ]),
      chips(
        ["Mon", "Tue", "Wed", "Thu"],
        ["Mon", "Tue", "Wed", "Thu"],
        "Learning days",
      ),
      card("Subjects", "7 active subjects", undefined, "Manage subjects"),
      card(
        "Archive profile",
        "Keeps records but removes Maya from new planning.",
        undefined,
        "Review",
      ),
    ],
    primaryAction: "Save changes",
    primaryTarget: "family-children",
  },
  {
    id: "people-permissions",
    group: "family-settings",
    eyebrow: "Family · People",
    title: "People & permissions",
    description: "Invite adults with the minimum access they need.",
    tab: "Family",
    blocks: [
      list([
        ["Sam R.", "Owner · full family and billing access", "You"],
        ["Jordan R.", "Parent · planning, logs and reports", "Active"],
        ["Auntie May", "Contributor · selected learning logs only", "Invited"],
      ]),
      notice(
        "Community identity",
        "Each adult controls their own Community profile and connections.",
      ),
      card(
        "Invite an adult",
        "Choose a role before sending the secure invitation.",
        undefined,
        "Invite",
        "mint",
      ),
    ],
    primaryAction: "Manage Jordan’s access",
    primaryTarget: "preferences",
  },
  {
    id: "preferences",
    group: "family-settings",
    eyebrow: "Family · Preferences",
    title: "Planning preferences",
    description: "Shape the app around your family rhythm.",
    tab: "Family",
    blocks: [
      list([
        ["Week starts", "Monday", "Edit"],
        ["Default activity duration", "45 minutes", "Edit"],
        ["Daily planning limit", "2 activities per child", "On"],
        ["Time format", "24 hour", "Edit"],
        ["Language", "English (UK)", "Edit"],
      ]),
      notice(
        "Calm defaults",
        "The app avoids streaks, rankings and pressure-based reminders.",
      ),
    ],
    primaryAction: "Save preferences",
    primaryTarget: "notifications",
  },
  {
    id: "notifications",
    group: "family-settings",
    eyebrow: "Family · Notifications",
    title: "Useful, not noisy",
    description: "Choose what deserves attention and when.",
    tab: "Family",
    blocks: [
      list([
        ["Today summary", "08:00 on learning days", "On"],
        ["Activity reminders", "15 minutes before", "On"],
        ["Tasks due", "Same day", "On"],
        ["Community hellos", "Immediately", "On"],
        ["Channel activity", "Daily digest", "On"],
        ["Meetups nearby", "Weekly", "Off"],
      ]),
      card(
        "Quiet hours",
        "20:30 – 07:30 · urgent account alerts only",
        "Active",
        "Edit",
      ),
    ],
    primaryAction: "Save notifications",
    primaryTarget: "membership",
  },
  {
    id: "membership",
    group: "family-settings",
    eyebrow: "Family · Membership",
    title: "NexSteps Home Plus",
    description:
      "The essentials stay clear; paid value is tied to deeper organisation.",
    tab: "Family",
    blocks: [
      card(
        "Current plan",
        "Home Plus · monthly · renews 18 August",
        "Active",
        "Manage",
      ),
      list([
        ["Included", "Unlimited learning logs and evidence"],
        ["Included", "Editable term reports"],
        ["Included", "Two adult family members"],
        ["Community", "Included while membership is active"],
      ]),
      notice(
        "No surprise changes",
        "Price and renewal date are shown before any plan change.",
        "yellow",
      ),
    ],
    primaryAction: "View plan options",
    primaryTarget: "privacy-data",
    secondaryAction: "Manage billing",
  },
  {
    id: "privacy-data",
    group: "family-settings",
    eyebrow: "Family · Privacy",
    title: "Your data, clearly controlled",
    description:
      "Export, retention and deletion are understandable and separated.",
    tab: "Family",
    blocks: [
      card(
        "Download family data",
        "Plans, logs, evidence metadata and account settings.",
        "ZIP + JSON",
        "Prepare export",
        "mint",
      ),
      card(
        "Download report archive",
        "All generated PDFs in one package.",
        "PDFs",
        "Prepare",
      ),
      card(
        "Community profile",
        "Pause or delete separately from family records.",
        "Optional",
        "Manage",
      ),
      card(
        "Delete family account",
        "Starts a protected confirmation and retention workflow.",
        "Permanent",
        "Review",
        "danger",
      ),
    ],
    primaryAction: "Prepare data export",
    primaryTarget: "account-session",
  },
  {
    id: "account-session",
    group: "family-settings",
    eyebrow: "Family · Account",
    title: "Account & sessions",
    description: "Secure access controls without technical language.",
    tab: "Family",
    blocks: [
      list([
        ["Email", "parent@example.com", "Verified"],
        ["Password", "Changed 42 days ago", "Change"],
        ["Two-step verification", "Authenticator app", "On"],
        ["This iPhone", "London · active now", "Current"],
        ["Mac browser", "London · yesterday", "Sign out"],
      ]),
      notice(
        "Lost a device?",
        "Sign out every other session without affecting this device.",
        "yellow",
      ),
    ],
    primaryAction: "Sign out other sessions",
    primaryTarget: "family-children",
    secondaryAction: "Sign out",
  },
  ...regulationsScreens,
  {
    id: "moderation-queue",
    group: "moderation",
    eyebrow: "Moderation",
    title: "Reports needing review",
    description: "Prioritised by risk, recency and repeated behaviour.",
    blocks: [
      chips(["Open 12", "High risk 3", "Assigned to me 4"], ["Open 12"]),
      list([
        ["NSH-4821 · Privacy", "Public post repeated a private detail", "High"],
        [
          "NSH-4819 · Unsafe meetup",
          "Home address requested in thread",
          "High",
        ],
        ["NSH-4814 · Harassment", "Repeated messages after decline", "Medium"],
        ["NSH-4808 · Spam", "Promotional links across channels", "Low"],
      ]),
    ],
    primaryAction: "Open NSH-4821",
    primaryTarget: "moderation-report",
  },
  {
    id: "moderation-report",
    group: "moderation",
    eyebrow: "Report NSH-4821",
    title: "Privacy concern",
    description: "Submitted today · reporter identity protected",
    blocks: [
      notice(
        "Immediate state",
        "Members are blocked from each other. Reported content is hidden pending review.",
        "yellow",
      ),
      card(
        "Reported post",
        "“I know Sam’s family is at … every Wednesday.”",
        "Channel post",
      ),
      card(
        "Reporter context",
        "Private detail was first shared in an adult introduction.",
        "1 attachment",
      ),
      card(
        "Reported member",
        "2 prior warnings · 1 removed post · member since March",
        "History",
        "View history",
      ),
    ],
    primaryAction: "Review member history",
    primaryTarget: "member-history",
    secondaryAction: "Escalate",
  },
  {
    id: "member-history",
    group: "moderation",
    eyebrow: "Member history",
    title: "Alex P.",
    description: "Account, content and prior decisions in one timeline.",
    blocks: [
      stats([
        ["2", "Warnings"],
        ["1", "Removed post"],
        ["0", "Suspensions"],
      ]),
      list([
        ["Today · NSH-4821", "Privacy concern · under review", "Open"],
        ["14 June · NSH-4490", "Personal contact in public post", "Warning"],
        ["3 May · NSH-4232", "Promotional posting", "Content removed"],
      ]),
      notice(
        "Decision support",
        "Use documented behaviour and policy; do not infer risk from family profile data.",
        "neutral",
      ),
    ],
    primaryAction: "Choose resolution",
    primaryTarget: "moderation-resolution",
  },
  {
    id: "moderation-resolution",
    group: "moderation",
    eyebrow: "Resolve NSH-4821",
    title: "Record a clear decision",
    description: "Every action is auditable and communicated appropriately.",
    blocks: [
      chips(
        ["No action", "Warning", "Remove content", "Suspend", "Escalate"],
        ["Remove content", "Warning"],
        "Actions",
      ),
      fields([
        [
          "Internal rationale",
          "Private location information was repeated publicly after prior guidance.",
        ],
      ]),
      list([
        ["Reporter update", "Concern upheld · content removed"],
        ["Member update", "Specific policy breached · warning issued"],
        ["Audit log", "Reviewer, timestamp, evidence and actions"],
      ]),
      notice(
        "Double-check impact",
        "Suspension and escalation require a second moderator review.",
        "yellow",
      ),
    ],
    primaryAction: "Save resolution",
    primaryTarget: "moderation-queue",
    secondaryAction: "Request second review",
  },
];

export const screensById = new Map(
  wireframeScreens.map((screen) => [screen.id, screen]),
);

export const firstScreenByTab: Record<AppTab, string> = {
  Week: "week-home",
  Today: "today",
  Community: "community-home",
  Progress: "progress-overview",
  Family: "family-children",
};
