import type { Vertical, Module } from "@prisma/client";
import type { Capability } from "./capability-definitions";

// These maps remain the commercial entitlement authority. Adding a
// Vertical/Module enum value without a mapping breaks the build.
const PLATFORM_CORE_CAPABILITIES = [
  "attendance.read",
  "attendance.manage",
  "platform.access.roles.read",
  "platform.access.roles.manage",
  "platform.access.permissions.read",
  "platform.access.assignments.read",
  "platform.access.assignments.manage",
  "platform.access.users.read",
  "platform.access.audit.read",
  "messaging.conversations.read",
  "messaging.conversations.create",
  "messaging.messages.read",
  "messaging.messages.send",
  "notices.read",
  "notices.manage",
  "notices.publish",
  "safeguarding.concerns.record",
  "safeguarding.concerns.read",
  "safeguarding.concerns.manage",
] as const satisfies readonly Capability[];

export const VERTICAL_CAPABILITIES = {
  CHURCH: [
    ...PLATFORM_CORE_CAPABILITIES,
    "volunteers.manage",
    "giving.manage",
    "calendar.read",
  ],
  INDEPENDENT_SCHOOL: [
    ...PLATFORM_CORE_CAPABILITIES,
    "students.manage",
    "classes.manage",
    "parents.read",
    "reports.read",
  ],
  ACE_SCHOOL: [
    ...PLATFORM_CORE_CAPABILITIES,
    "students.manage",
    "classes.manage",
    "pace.manage",
    "parents.read",
    "reports.read",
    "ace.settings.read",
    "ace.settings.manage",
    "ace.pace.read",
    "ace.pace.record",
    "ace.pace.correct",
    "ace.pace.override",
    "ace.behaviour.read",
    "ace.behaviour.record",
    "ace.behaviour.sensitive.read",
    "ace.behaviour.policy.manage",
    "ace.reports.read",
    "ace.reports.compile",
    "ace.reports.review",
    "ace.reports.publish",
    "ace.parent.progress.read",
    "ace.student.self.read",
    "ace.faith.read",
    "ace.faith.manage",
    "ace.faith.publish",
    "ace.faith.reflect",
    "ace.community.read",
    "ace.community.post",
    "ace.community.report",
    "ace.community.spaces.manage",
    "ace.community.settings.manage",
    "ace.community.moderate",
    "school.trips.read",
    "school.trips.manage",
    "school.permission_slips.read",
    "school.permission_slips.manage",
    "school.permission_slips.respond",
    "learning.log.read",
    "learning.log.write",
    "learning.evidence.read",
    "learning.evidence.write",
    "learning.reports.generate",
  ],
  STATE_SCHOOL: [
    ...PLATFORM_CORE_CAPABILITIES,
    "students.manage",
    "classes.manage",
    "parents.read",
    "reports.read",
  ],
  NURSERY: [
    ...PLATFORM_CORE_CAPABILITIES,
    "children.manage",
    "parents.read",
  ],
  CHARITY: [
    ...PLATFORM_CORE_CAPABILITIES,
    "volunteers.manage",
    "calendar.read",
  ],
  CLUB: [
    ...PLATFORM_CORE_CAPABILITIES,
    "members.manage",
    "calendar.read",
  ],
  HOME_EDUCATION: [
    ...PLATFORM_CORE_CAPABILITIES,
    "learning.log.read",
    "learning.log.write",
    "learning.evidence.read",
    "learning.evidence.write",
    "learning.reports.generate",
    "family.activities.read",
    "family.activities.write",
    "family.tasks.read",
    "family.tasks.write",
    "family.calendar.read",
    "family.calendar.write",
  ],
} as const satisfies Record<Vertical, readonly Capability[]>;

export const MODULE_CAPABILITIES = {
  FINANCE: [
    "finance.invoices",
    "finance.payments",
    "finance.reports",
    "finance.family_invoices.read",
    "finance.family_invoices.manage",
    "finance.family_payments.record",
    "finance.family_reports.read",
  ],
  EVENTS: ["events.booking", "events.manage"],
  TRANSPORT: ["transport.routes", "transport.manage"],
  MEALS: ["meals.manage", "meals.orders"],
  ASSET_MANAGEMENT: ["assets.manage", "assets.audit"],
  HR: ["hr.staff", "hr.leave"],
  AI_WORKSPACE: ["ai.workspace"],
  ADVANCED_REPORTING: [
    "reporting.advanced",
    "advanced_reporting.ace.multisite.read",
  ],
  LEARNING: [
    "learning.log.read",
    "learning.log.write",
    "learning.evidence.read",
    "learning.evidence.write",
    "learning.reports.generate",
  ],
} as const satisfies Record<Module, readonly Capability[]>;
