import { Module, Vertical } from "@prisma/client";

export type PermissionScope =
  | "organisation"
  | "site"
  | "relationship"
  | "assignment";

export type PermissionSensitivity = "standard" | "sensitive" | "protected";

/**
 * A permission key opts into this layer explicitly. Most keys have no
 * feature toggle at all, meaning the layer is genuinely inapplicable to
 * them (see docs/ace-vertical/01-source-and-access-matrix.md, "`none` means
 * the layer is genuinely inapplicable to that route. It never means
 * undecided.").
 */
export type FeatureToggle = "ace.student_community";

export interface CapabilityDefinition {
  label: string;
  description: string;
  scope: PermissionScope;
  sensitivity: PermissionSensitivity;
  delegable: boolean;
  requiredModule?: Module;
  requiredVertical?: Vertical;
  featureToggle?: FeatureToggle;
}

type CapabilityRequirement = Pick<
  CapabilityDefinition,
  "requiredModule" | "requiredVertical" | "featureToggle"
>;

function defineCapability(
  label: string,
  description: string,
  scope: PermissionScope,
  sensitivity: PermissionSensitivity,
  delegable = true,
  requirement: CapabilityRequirement = {},
): CapabilityDefinition {
  return {
    label,
    description,
    scope,
    sensitivity,
    delegable,
    ...requirement,
  };
}

const aceRequirement = { requiredVertical: Vertical.ACE_SCHOOL } as const;

export const CAPABILITY_DEFINITIONS = {
  "attendance.read": defineCapability(
    "View attendance",
    "View attendance records for the active site",
    "site",
    "standard",
  ),
  "attendance.manage": defineCapability(
    "Manage attendance",
    "Record and manage attendance for the active site",
    "site",
    "standard",
  ),
  "volunteers.manage": defineCapability(
    "Manage volunteers",
    "Manage volunteer records for the active site",
    "site",
    "standard",
  ),
  "giving.manage": defineCapability(
    "Manage giving",
    "Manage giving records for the active site",
    "site",
    "standard",
    true,
    { requiredVertical: Vertical.CHURCH },
  ),
  "calendar.read": defineCapability(
    "View calendar",
    "View the active site's calendar",
    "site",
    "standard",
  ),
  "students.manage": defineCapability(
    "Manage students",
    "Manage student records for the active site",
    "site",
    "sensitive",
  ),
  "classes.manage": defineCapability(
    "Manage classes",
    "Manage classes for the active site",
    "site",
    "standard",
  ),
  "parents.read": defineCapability(
    "View parents and guardians",
    "View parent and guardian records for the active site",
    "site",
    "sensitive",
  ),
  "reports.read": defineCapability(
    "View reports",
    "View reports for the active site",
    "site",
    "sensitive",
  ),
  "pace.manage": defineCapability(
    "Manage PACE",
    "Manage legacy PACE records for the active site",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "children.manage": defineCapability(
    "Manage children",
    "Manage child records for the active site",
    "site",
    "sensitive",
    true,
    { requiredVertical: Vertical.NURSERY },
  ),
  "members.manage": defineCapability(
    "Manage members",
    "Manage member records for the active site",
    "site",
    "standard",
    true,
    { requiredVertical: Vertical.CLUB },
  ),
  "finance.invoices": defineCapability(
    "Access invoices",
    "Access legacy Finance invoice operations",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.FINANCE },
  ),
  "finance.payments": defineCapability(
    "Access payments",
    "Access legacy Finance payment operations",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.FINANCE },
  ),
  "finance.reports": defineCapability(
    "View finance reports",
    "View legacy Finance reports",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.FINANCE },
  ),
  "events.booking": defineCapability(
    "Book events",
    "Book events for the active site",
    "site",
    "standard",
    true,
    { requiredModule: Module.EVENTS },
  ),
  "events.manage": defineCapability(
    "Manage events",
    "Manage events for the active site",
    "site",
    "standard",
    true,
    { requiredModule: Module.EVENTS },
  ),
  "transport.routes": defineCapability(
    "View transport routes",
    "View transport routes for the active site",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.TRANSPORT },
  ),
  "transport.manage": defineCapability(
    "Manage transport",
    "Manage transport for the active site",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.TRANSPORT },
  ),
  "meals.manage": defineCapability(
    "Manage meals",
    "Manage meal services for the active site",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.MEALS },
  ),
  "meals.orders": defineCapability(
    "View meal orders",
    "View meal orders for the active site",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.MEALS },
  ),
  "assets.manage": defineCapability(
    "Manage assets",
    "Manage organisation assets",
    "site",
    "standard",
    true,
    { requiredModule: Module.ASSET_MANAGEMENT },
  ),
  "assets.audit": defineCapability(
    "Audit assets",
    "Audit organisation assets",
    "site",
    "standard",
    true,
    { requiredModule: Module.ASSET_MANAGEMENT },
  ),
  "hr.staff": defineCapability(
    "Access staff records",
    "Access organisation staff records",
    "organisation",
    "sensitive",
    true,
    { requiredModule: Module.HR },
  ),
  "hr.leave": defineCapability(
    "Access leave records",
    "Access organisation leave records",
    "organisation",
    "sensitive",
    true,
    { requiredModule: Module.HR },
  ),
  "ai.workspace": defineCapability(
    "Use AI Workspace",
    "Use the organisation AI workspace",
    "organisation",
    "standard",
    true,
    { requiredModule: Module.AI_WORKSPACE },
  ),
  "reporting.advanced": defineCapability(
    "View advanced reporting",
    "View organisation advanced reporting",
    "organisation",
    "sensitive",
    true,
    { requiredModule: Module.ADVANCED_REPORTING },
  ),
  "learning.log.read": defineCapability(
    "View learning logs",
    "View learning activity logs",
    "site",
    "sensitive",
  ),
  "learning.log.write": defineCapability(
    "Record learning activity",
    "Create learning log entries",
    "site",
    "sensitive",
  ),
  "learning.evidence.read": defineCapability(
    "View learning evidence",
    "View learning evidence attachments",
    "site",
    "sensitive",
  ),
  "learning.evidence.write": defineCapability(
    "Add learning evidence",
    "Attach learning evidence",
    "site",
    "sensitive",
  ),
  "learning.reports.generate": defineCapability(
    "Generate learning reports",
    "Generate learning progress reports",
    "site",
    "sensitive",
  ),
  "family.activities.read": defineCapability(
    "View planned activities",
    "View the household's planned learning activities",
    "site",
    "sensitive",
  ),
  "family.activities.write": defineCapability(
    "Plan activities",
    "Create and edit the household's planned learning activities",
    "site",
    "sensitive",
  ),
  "family.tasks.read": defineCapability(
    "View family tasks",
    "View the household's tasks",
    "site",
    "sensitive",
  ),
  "family.tasks.write": defineCapability(
    "Manage family tasks",
    "Create, assign and complete the household's tasks",
    "site",
    "sensitive",
  ),
  "family.calendar.read": defineCapability(
    "View family calendar",
    "View the household's private calendar items",
    "site",
    "sensitive",
  ),
  "family.calendar.write": defineCapability(
    "Manage family calendar",
    "Create and edit the household's private calendar items",
    "site",
    "sensitive",
  ),
  "family.regulations.read": defineCapability(
    "View regulations and evidence",
    "View the household's preparedness, official requirements, updates, linked evidence and correspondence",
    "site",
    "sensitive",
  ),
  "family.regulations.write": defineCapability(
    "Manage regulations and evidence",
    "Set the household's jurisdiction, update preparedness, link evidence and record correspondence",
    "site",
    "sensitive",
  ),
  "platform.access.roles.read": defineCapability(
    "View roles",
    "View organisation role definitions",
    "organisation",
    "protected",
    false,
  ),
  "platform.access.roles.manage": defineCapability(
    "Manage roles",
    "Create, edit, clone, retire, and configure roles",
    "organisation",
    "protected",
    false,
  ),
  "platform.access.permissions.read": defineCapability(
    "View permission registry",
    "View active platform-owned permission metadata",
    "organisation",
    "protected",
    false,
  ),
  "platform.access.assignments.read": defineCapability(
    "View role assignments",
    "View organisation role assignments",
    "organisation",
    "protected",
    false,
  ),
  "platform.access.assignments.manage": defineCapability(
    "Manage role assignments",
    "Create and remove organisation role assignments",
    "organisation",
    "protected",
    false,
  ),
  "platform.access.users.read": defineCapability(
    "View user access",
    "View user effective permissions and access summaries",
    "organisation",
    "protected",
    false,
  ),
  "platform.access.audit.read": defineCapability(
    "View access audit",
    "View organisation access-audit events",
    "organisation",
    "protected",
    false,
  ),
  "messaging.conversations.read": defineCapability(
    "View conversations",
    "View conversations within the actor's permitted relationships",
    "relationship",
    "sensitive",
  ),
  "messaging.conversations.create": defineCapability(
    "Create conversations",
    "Create conversations within the actor's permitted relationships",
    "relationship",
    "sensitive",
  ),
  "messaging.messages.read": defineCapability(
    "View messages",
    "View messages within the actor's permitted conversations",
    "relationship",
    "sensitive",
  ),
  "messaging.messages.send": defineCapability(
    "Send messages",
    "Send messages within the actor's permitted conversations",
    "relationship",
    "sensitive",
  ),
  "notices.read": defineCapability(
    "View notices",
    "View notices for the active site",
    "site",
    "standard",
  ),
  "notices.manage": defineCapability(
    "Manage notices",
    "Create and manage notice drafts for the active site",
    "site",
    "standard",
  ),
  "notices.publish": defineCapability(
    "Publish notices",
    "Publish notices to an approved audience",
    "site",
    "protected",
  ),
  "safeguarding.concerns.record": defineCapability(
    "Record safeguarding concerns",
    "Record safeguarding concerns for the active site",
    "site",
    "sensitive",
  ),
  "safeguarding.concerns.read": defineCapability(
    "View safeguarding concerns",
    "View safeguarding concerns within an assigned domain",
    "assignment",
    "protected",
    false,
  ),
  "safeguarding.concerns.manage": defineCapability(
    "Manage safeguarding concerns",
    "Manage safeguarding concerns within an assigned domain",
    "assignment",
    "protected",
    false,
  ),
  "ace.dashboard.read": defineCapability(
    "View ACE dashboard",
    "View the active site's ACE operations overview",
    "site",
    "standard",
    true,
    aceRequirement,
  ),
  "ace.settings.read": defineCapability(
    "View ACE settings",
    "View ACE and academic-year configuration",
    "site",
    "standard",
    true,
    aceRequirement,
  ),
  "ace.settings.manage": defineCapability(
    "Manage ACE settings",
    "Update ACE and academic-year configuration",
    "site",
    "standard",
    true,
    aceRequirement,
  ),
  "ace.pace.read": defineCapability(
    "View PACE progress",
    "View PACE rosters, progress, and exceptions",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.pace.record": defineCapability(
    "Record PACE assessments",
    "Create PACE subjects and assessments",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.pace.correct": defineCapability(
    "Correct PACE assessments",
    "Add an auditable PACE correction",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.pace.override": defineCapability(
    "Override PACE policy",
    "Authorise a time-bounded PACE policy override",
    "site",
    "protected",
    true,
    aceRequirement,
  ),
  "ace.pace.inventory.read": defineCapability(
    "View PACE inventory",
    "View physical PACE stock and orders for the active site",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.pace.inventory.manage": defineCapability(
    "Manage PACE inventory",
    "Record physical PACE stock and delivery for the active site",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.behaviour.read": defineCapability(
    "View behaviour",
    "View behaviour records and policy",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.behaviour.record": defineCapability(
    "Record behaviour",
    "Create and correct behaviour facts",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.behaviour.sensitive.read": defineCapability(
    "View sensitive behaviour",
    "View restricted fields in behaviour records",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.behaviour.policy.manage": defineCapability(
    "Manage behaviour policy",
    "Update the active behaviour policy",
    "site",
    "standard",
    true,
    aceRequirement,
  ),
  "ace.reports.read": defineCapability(
    "View ACE reports",
    "View and download ACE reports within release policy",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.reports.compile": defineCapability(
    "Compile ACE reports",
    "Generate an ACE report snapshot",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.reports.review": defineCapability(
    "Review ACE reports",
    "Submit and approve ACE reports under maker-checker policy",
    "site",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.reports.publish": defineCapability(
    "Publish ACE reports",
    "Publish and freeze an ACE report version",
    "site",
    "protected",
    true,
    aceRequirement,
  ),
  "ace.parent.progress.read": defineCapability(
    "View family ACE progress",
    "View a linked child's released ACE summary and reports",
    "relationship",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.student.self.read": defineCapability(
    "View student ACE progress",
    "View the authenticated student's released ACE data",
    "relationship",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.faith.read": defineCapability(
    "View Faith content",
    "View published Faith content and permitted reflections",
    "relationship",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.faith.manage": defineCapability(
    "Manage Faith content",
    "Create and manage Faith content drafts",
    "site",
    "standard",
    true,
    aceRequirement,
  ),
  "ace.faith.publish": defineCapability(
    "Publish Faith content",
    "Publish Faith content to an approved audience",
    "site",
    "protected",
    true,
    aceRequirement,
  ),
  "ace.faith.reflect": defineCapability(
    "Add Faith reflections",
    "Add a reflection to permitted published Faith content",
    "relationship",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.community.read": defineCapability(
    "View Student Community",
    "View permitted Student Community spaces and posts",
    "relationship",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.community.post": defineCapability(
    "Post to Student Community",
    "Create a post in a permitted community space",
    "relationship",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.community.report": defineCapability(
    "Report Community content",
    "Report a post for moderation",
    "relationship",
    "sensitive",
    true,
    aceRequirement,
  ),
  "ace.community.spaces.manage": defineCapability(
    "Manage Community spaces",
    "Create and administer Student Community spaces",
    "site",
    "standard",
    true,
    aceRequirement,
  ),
  "ace.community.settings.manage": defineCapability(
    "Manage Community settings",
    "Enable or disable Student Community for a site",
    "site",
    "standard",
    true,
    aceRequirement,
  ),
  "ace.community.moderate": defineCapability(
    "Moderate Student Community",
    "Moderate reported Student Community content",
    "assignment",
    "protected",
    true,
    aceRequirement,
  ),
  "school.trips.read": defineCapability(
    "View trips",
    "View trips for the active site",
    "site",
    "standard",
  ),
  "school.trips.manage": defineCapability(
    "Manage trips",
    "Create and update active-site trips",
    "site",
    "standard",
  ),
  "school.permission_slips.read": defineCapability(
    "View permission slips",
    "View eligible trip permission slips and responses",
    "relationship",
    "sensitive",
  ),
  "school.permission_slips.manage": defineCapability(
    "Manage permission slips",
    "Create and publish versioned permission slips",
    "site",
    "protected",
  ),
  "school.permission_slips.respond": defineCapability(
    "Respond to permission slips",
    "Record a guardian response for an eligible child",
    "relationship",
    "sensitive",
  ),
  "clubs.read": defineCapability(
    "View clubs",
    "View permitted clubs, rosters, and notices",
    "assignment",
    "sensitive",
  ),
  "clubs.manage": defineCapability(
    "Manage clubs",
    "Manage clubs and assigned-club operations",
    "assignment",
    "sensitive",
  ),
  "clubs.signup.manage": defineCapability(
    "Manage club sign-ups",
    "Manage club sign-ups and rosters",
    "assignment",
    "sensitive",
  ),
  "clubs.attendance.record": defineCapability(
    "Record club attendance",
    "Record attendance for assigned club sessions",
    "assignment",
    "sensitive",
  ),
  "clubs.leads.manage": defineCapability(
    "Manage club leads",
    "Assign and manage scoped club leads",
    "site",
    "sensitive",
  ),
  "finance.family_invoices.read": defineCapability(
    "View family invoices",
    "View family invoices and eligible downloads",
    "relationship",
    "sensitive",
    true,
    { requiredModule: Module.FINANCE },
  ),
  "finance.family_invoices.manage": defineCapability(
    "Manage family invoices",
    "Draft, issue, void, and credit family invoices",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.FINANCE },
  ),
  "finance.family_payments.record": defineCapability(
    "Record family payments",
    "Record and allocate family payments",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.FINANCE },
  ),
  "finance.family_reports.read": defineCapability(
    "View family finance reports",
    "View aged receivables and family finance reports",
    "site",
    "sensitive",
    true,
    { requiredModule: Module.FINANCE },
  ),
  "merit.wallet.read": defineCapability(
    "View merit wallets",
    "View a child's virtual merit wallet and ledger",
    "relationship",
    "sensitive",
  ),
  "merit.wallet.adjust": defineCapability(
    "Adjust merit wallets",
    "Create a reasoned virtual-merit adjustment",
    "site",
    "sensitive",
  ),
  "merit.wallet.transfer": defineCapability(
    "Transfer merit",
    "Transfer virtual merit between permitted accounts",
    "relationship",
    "sensitive",
  ),
  "merit.tithe.manage": defineCapability(
    "Manage merit tithe",
    "Manage virtual-merit giving and tithe rules",
    "site",
    "sensitive",
  ),
  "merit.shop.read": defineCapability(
    "View Merit Shop",
    "View shop items and reservations",
    "relationship",
    "standard",
  ),
  "merit.shop.manage": defineCapability(
    "Manage Merit Shop",
    "Manage shop items and reservations",
    "site",
    "standard",
  ),
  "merit.shop.purchase": defineCapability(
    "Purchase from Merit Shop",
    "Spend virtual merit on an eligible shop item",
    "relationship",
    "sensitive",
  ),
  "merit.market.read": defineCapability(
    "View Merit Market",
    "View simulated market instruments and portfolio",
    "relationship",
    "sensitive",
  ),
  "merit.market.trade": defineCapability(
    "Trade in Merit Market",
    "Place a simulated market order",
    "relationship",
    "sensitive",
  ),
  "merit.leaderboards.read": defineCapability(
    "View merit leaderboards",
    "View permitted positive merit leaderboards",
    "relationship",
    "sensitive",
  ),
  "advanced_reporting.ace.multisite.read": defineCapability(
    "View ACE multi-site reporting",
    "View approved aggregate ACE metrics across sites",
    "organisation",
    "sensitive",
    true,
    { requiredModule: Module.ADVANCED_REPORTING },
  ),
} as const satisfies Record<string, CapabilityDefinition>;

export type Capability = keyof typeof CAPABILITY_DEFINITIONS;
export type PermissionKey = Capability;
