import { SYSTEM_ROLE_TEMPLATES } from "./system-role-templates";

describe("ACE system role templates", () => {
  it("defines the approved protected template scopes and permission mappings", () => {
    expect(SYSTEM_ROLE_TEMPLATES).toEqual({
      organisationHead: {
        name: "Organisation Head",
        scope: "organisation",
        protected: true,
        permissions: [
          "platform.access.roles.read",
          "platform.access.roles.manage",
          "platform.access.permissions.read",
          "platform.access.assignments.read",
          "platform.access.assignments.manage",
          "platform.access.users.read",
          "platform.access.audit.read",
          "ace.settings.read",
          "ace.settings.manage",
          "ace.pace.read",
          "ace.pace.record",
          "ace.pace.correct",
          "ace.pace.override",
          "ace.behaviour.read",
          "ace.behaviour.record",
          "ace.behaviour.policy.manage",
          "ace.reports.read",
          "ace.reports.review",
          "ace.reports.publish",
          "ace.faith.read",
          "ace.faith.manage",
          "ace.faith.publish",
          "ace.community.read",
          "ace.community.report",
          "ace.community.spaces.manage",
          "ace.community.settings.manage",
          "ace.community.moderate",
          "school.trips.read",
          "school.trips.manage",
          "school.permission_slips.read",
          "school.permission_slips.manage",
        ],
      },
      siteLead: {
        name: "Site Lead",
        scope: "site",
        protected: true,
        permissions: [
          "ace.settings.read",
          "ace.settings.manage",
          "ace.pace.read",
          "ace.pace.record",
          "ace.pace.correct",
          "ace.pace.override",
          "ace.behaviour.read",
          "ace.behaviour.record",
          "ace.behaviour.policy.manage",
          "ace.reports.read",
          "ace.reports.compile",
          "ace.reports.review",
          "ace.reports.publish",
          "ace.faith.read",
          "ace.faith.manage",
          "ace.faith.publish",
          "ace.community.read",
          "ace.community.report",
          "ace.community.spaces.manage",
          "ace.community.moderate",
          "school.trips.read",
          "school.trips.manage",
          "school.permission_slips.read",
          "school.permission_slips.manage",
        ],
      },
      staff: {
        name: "Staff",
        scope: "site",
        protected: true,
        permissions: [
          "ace.settings.read",
          "ace.pace.read",
          "ace.pace.record",
          "ace.behaviour.read",
          "ace.behaviour.record",
          "ace.reports.read",
          "ace.reports.compile",
          "ace.reports.review",
          "ace.faith.read",
          "ace.faith.manage",
          "ace.community.read",
          "ace.community.post",
          "ace.community.report",
          "school.trips.read",
          "school.trips.manage",
          "school.permission_slips.read",
          "school.permission_slips.manage",
        ],
      },
      safeguardingLead: {
        name: "Safeguarding Lead",
        scope: "site",
        protected: true,
        permissions: ["ace.behaviour.read"],
      },
      financeOperator: {
        name: "Finance Operator",
        scope: "organisation",
        protected: true,
        permissions: [],
      },
      parent: {
        name: "Parent",
        scope: "relationship",
        protected: true,
        permissions: [
          "ace.parent.progress.read",
          "ace.faith.read",
          "ace.faith.reflect",
          "school.permission_slips.read",
          "school.permission_slips.respond",
        ],
      },
      student: {
        name: "Student",
        scope: "relationship",
        protected: true,
        permissions: [
          "ace.student.self.read",
          "ace.faith.read",
          "ace.faith.reflect",
          "ace.community.read",
          "ace.community.post",
          "ace.community.report",
        ],
      },
    });
  });
});
